


# map data
map_name: "example_map"
map_ext: ".png"

# starting positions for vehicle
sx: 0.0
sy: 0.0
stheta: 1.37079632679 

mu: 0.523
m: 3.47
g: 9.81
l_r: 0.17
l_f: 0.158
force_f: 
max_v: 7
max_a: 8.5

lookahead: 2
v_gain: 0.9
force_f: 0.8

